spring:
    application:
        name: data-visual
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        initialization-mode: always
        password: sanjaylakum
        url: jdbc:mysql://localhost:3306/data
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
        show-sql: true